### ISSUE TITLE
Crash app flutter

### ISSUE THREAD

**Issue by Proton-V** [proteye/facebook_deeplinks#2]
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask
at ru.proteye.facebook_deeplinks.FacebookDeeplinksPlugin.handleLink(FacebookDeeplinksPlugin.java:163)
        at ru.proteye.facebook_deeplinks.FacebookDeeplinksPlugin.access$100(FacebookDeeplinksPlugin.java:25)
        at ru.proteye.facebook_deeplinks.FacebookDeeplinksPlugin$1.onDeferredAppLinkDataFetched(FacebookDeeplinksPlugin.java:114)
        at com.facebook.applinks.AppLinkData.fetchDeferredAppLinkFromServer(AppLinkData.java:248)
        at com.facebook.applinks.AppLinkData.access$000(AppLinkData.java:50)
        at com.facebook.applinks.AppLinkData$1.run(AppLinkData.java:151)

**Comment by Proton-V** [comment]
Only with release apk
